# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
  batch: 
    'true'
  branches:
    include:
    - master

pool:
  vmImage: 'VS2017-Win2016'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  outputFile: '$(Build.BuildId)'

steps:
- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: '$Revision = git describe --first-parent --always;
    $Version=Get-Content "./Program/Version.txt" -First 1;
    $Revision = "$Version-$(Build.BuildId)-$Revision";
    Set-Content "./Program/Revision.txt" "`$Revision: $Revision `$";
    (Get-Content "./Program/Version.txt" | select -skip 1 )| Set-Content "./Program/Version.txt";
    $Version=Get-Content "./Program/Version.txt" -First 1;
    $Version="$Version$Revision";
    Write-Host "##vso[task.setvariable variable=outputFile]$Version";
    git log --pretty=format:"%h|%ad|%an|%s" --date=format:"%Y-%m-%dT%H:%MZ" -100 | ConvertFrom-Csv -Delimiter "|" -Header "Commit", "Date", "Author", "Message" | ConvertTo-Json | %{[Regex]::Replace($_, "\\u(?<Value>[a-zA-Z0-9]{4})", { param($m) ([char]([int]::Parse($m.Groups["Value"].Value,[System.Globalization.NumberStyles]::HexNumber))).ToString() } )} | Out-File $(Build.ArtifactStagingDirectory)/history.json;
@{version="$Version";date=(get-date).ToString("yyyy-MM-ddTHH:mmZ");url="ci-builds/releases/$Version.zip"}| ConvertTo-Json | Out-File $(Build.ArtifactStagingDirectory)/version.json'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: './Program/'
    includeRootFolder: true 
    archiveFile: "$(Build.ArtifactStagingDirectory)/$(outputFile).zip"  

- task: AzureFileCopy@3
  inputs:
    SourcePath: '$(Build.ArtifactStagingDirectory)/$(outputFile).zip'
    ConnectedServiceNameARM: 'Visual Studio Enterprise(81c98ddc-0e66-422e-af90-10337e5c2352)'
    Destination: 'AzureBlob'
    StorageAccountRM: 'ultimaterails'
    ContainerName: 'ci-builds'
    BlobPrefix: 'releases'

- task: AzureFileCopy@3
  inputs:
    SourcePath: '$(Build.ArtifactStagingDirectory)'
    ConnectedServiceNameARM: 'Visual Studio Enterprise(81c98ddc-0e66-422e-af90-10337e5c2352)'
    Destination: 'AzureBlob'
    StorageAccountRM: 'ultimaterails'
    ContainerName: 'ci-builds'
    additionalArgumentsForBlobCopy: '/Pattern:*.json /Y'